language: ruby
rvm:
  - 2.0.0
env:
  - KREUBB_TOKEN="bc984d6b42a0e3883feee7b7d5c02943f77b4e8b29768ac6e2a1a931cfa1b180be68bf675949d44f27dc03fb5b653debe15a7f9bca9d14e3f26e4c0237eb4866"
services:
  - memcached
  - mongodb
before_install:
  - gem install bundler
script:
  - bundle exec rspec
  - bundle exec cucumber
bundler_args: --path vendor/bundle
