modules:
  - name: 'app'
  - name: 'static'
paths:
  tpl: "lib/tpl"
  handlebars: "lib/handlebars"
  bootstrap: "twitter/bootstrap"
  backbone: "lib/backbone"
  marionette: "lib/backbone.marionette"
  underscore: "lib/lodash"
  shims: "lib/shims"
shim:
  jquery_ujs: ['jquery']
  shims: ['jquery']
  timeago: ['jquery']
  bootstrap: ['jquery']
  js-routes:
    deps: ['jquery']
    exports: 'Routes'
