modules:
  - name: 'app'
  - name: 'static'
priority: ['jquery']
paths:
  tpl: "lib/tpl"
  handlebars: "lib/handlebars"
  bootstrap: "twitter/bootstrap"
  backbone: "lib/backbone"
  marionette: "lib/backbone.marionette"
  underscore: "lib/lodash"
  shims: "lib/shims"
  store: "lib/store"
  pusher: "http://js.pusher.com/1.12/pusher.min.js"
  jquery: 'lib/jquery'
shim:
  jquery_ujs: ['jquery']
  shims: ['jquery']
  timeago: ['jquery']
  bootstrap: ['jquery']
  js-routes:
    deps: ['jquery']
    exports: 'Routes'
