modules:
  - name: 'app'
  - name: 'static'
paths:
  bootstrap: "twitter/bootstrap"
  backbone: "lib/backbone"
  marionette: "lib/backbone.marionette"
  underscore: "lib/lodash"
  modernizr: "lib/modernizr"
  placeholder: "lib/placeholder.shim"
  timeago: "lib/timeago"
  io: "http://krisbb-node.dev/socket.io/socket.io.js"
shim:
  jquery_ujs: ['jquery']
  placeholder: ['jquery']
  timeago: ['jquery']
  bootstrap: ['jquery']
