enable_signup: false
assethost:
  email: 'http://assets.forum.kristjanrang.eu/assets'
  fog: 'http://krisbb-assets.s3.amazonaws.com'
  production: '//assets.forum.kristjanrang.eu'
gitsha: <%= `git log -1 --format="%H"`[0..6] %>
pusher:
  secret: 591850c3efee7ee4d2ff
public:
  pusher:
    app_id: 31206
    key: f134ecf4e059f85f6671
    endpoint: /pusher/auth
