enable_signup: false
assethost:
  email: 'http://assets.forum.kristjanrang.eu/assets'
  fog: 'http://krisbb-assets.s3.amazonaws.com'
  production: '//assets.forum.kristjanrang.eu'
gitsha: <%= `git log -1 --format="%H"`[0..6] %>
pusher:
  secret: <%= ENV['PUSHER_SECRET'] %>
public:
  pusher:
    app_id: 27770
    key: bb6ee2e971248c187d7c
    endpoint: /pusher/auth
