enable_signup: false
public:
  pusher:
    app_id: 27770
    key: bb6ee2e971248c187d7c
    endpoint: /pusher/auth
assethost:
  email: 'http://krisbb-assets.s3.amazonaws.com/assets'
  fog: 'http://krisbb-assets.s3.amazonaws.com'
  production: '//krisbb-assets.s3.amazonaws.com'
pusher:
  secret: <%= ENV['PUSHER_SECRET'] %>
gitsha: <%= `git log -1 --format="%H"`[0..6] %>
